version: '3.1'
services:
  # API:
  #   image: 'libreria-be'
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     PostgreSQL:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=root
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  PostgreSQL:
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/pgdata:/var/lib/postgresql/data
    container_name: db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=libreria
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5